### ISSUE TITLE
Catalina: The installer resources were not found.

### ISSUE THREAD

**Issue by JonnyTech** [eprigorodov/mkosxinstallusb#9]
The message occurs when making a bootable drive using Linux for Catalina. Any ideas?

![IMG_20201117_203850](https://user-images.githubusercontent.com/3584732/99445706-d8021800-2915-11eb-945f-608f43f34e42.png)

List of files on the drive: [filelist.txt](https://github.com/eprigorodov/mkosxinstallusb/files/5556147/filelist.txt)

**Comment by eprigorodov** [comment]
That is essentially the same as #1: since High Sierra Apple changed something in the installer media so that this very method does not work anymore. 

You can find a kind of solution in forked repositories.

**Comment by JonnyTech** [comment]
OK, thanks.
